# Module 4 Assignment: Ian Feekes NLP Basics Assignment

This notebook contains all content for USD MSAAI NLP Fundamentals Class for Ian Feekes' Module 4 Assignment. Thank you for taking the time to grade my work and to help me grow with your feedback.

If any work here does not end up in the correct location in blackboard, or does not meet standards or expectations, please let me know and I will gratefully and expediently make corrections. (ifeekes@sandiego.edu, 916-333-9381)

## Task 1: Import pandas and Read in quora_questions.csv file

This notebook is composed and ran locally, so the quora_questions.csv file will be imported from the same directory in which this .ipynb file resides. 

In [39]:
# import the pandas library
import pandas as pd

# hard-coded path for the csv file
dataFilePath = './quora_questions.csv'

# read the csv file into data frame structure df
df = pd.read_csv(dataFilePath)

# break if something went wrong with loading
assert(df.shape[0] > 0 and df.shape[1] > 0)

# spit out the first 5 entries of the data frame
df.head()

Question
0  What is the step by step guide to invest in sh...
1  What is the story of Kohinoor (Koh-i-Noor) Dia...
2  How can I increase the speed of my internet co...
3  Why am I mentally very lonely? How can I solve...
4  Which one dissolve in water quikly sugar, salt...

## Task 2: Preprocessing: Use TF-IDF Vectorization to create a vectorized document term matrix. You may want to explore the max_df and min_df parameters

In [40]:
# Import TF-IDF Vectorizer using sci-kit learn
from sklearn.feature_extraction.text import TfidfVectorizer

# Ignore the terms that appear in more than 50% of the documents
maxDf = 0.95
# Ignore the terms that appear in less than 1% of the documents
minDf = 2

# Initialize structure
v = TfidfVectorizer(min_df = minDf, max_df = maxDf)
x = v.fit_transform(df['Question'])
x

<404289x38972 sparse matrix of type '<class 'numpy.float64'>'
	with 4002064 stored elements in Compressed Sparse Row format>

## Task 3: Non-negative Matrix Factorization

TASK: Using Scikit-Learn create an instance of NMF with 20 expected components. (Use random state=42).

In [41]:
# Import scikit-learn Non-negative Matrix Factorization
from sklearn.decomposition import NMF

nmf_model = NMF(beta_loss='frobenius', init=None, l1_ratio=0.0, max_iter=200, n_components = 20,
                random_state=42, shuffle=False, solver='cd', tol=0.0001, verbose=0)
nmf_model.fit(x)

NMF(n_components=20, random_state=42)

TASK: Print out the top 15 most common words for each of the 20 topics

In [42]:
import random

for i in range(15):
    # Note: get_feature_names is depricated, using new function instead
    random_word_id = random.randint(0, len(v.get_feature_names_out()))
    print(v.get_feature_names_out()[random_word_id])

deepika
zuckerberg
dresden
jazz
halfhand
papers
rom
fade
arkham
discounts
iiser
webflow
dependant
feathers
mayhem


In [43]:
len(nmf_model.components_)

20

In [44]:
nmf_model.components_

array([[2.78675197e-03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.05994678e-04, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.35053620e-05, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 1.11400208e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.07294173e-04, 4.74667823e-03, 3.89814157e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.94484834e-03, 7.98495003e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [45]:
len(nmf_model.components_[0])

38972

In [46]:
for index, topic in enumerate(nmf_model.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #{index}")
    print([v.get_feature_names_out()[i] for i in topic.argsort()[-15:]], end = "\n\n")

THE TOP 15 WORDS FOR TOPIC #0
['effects', 'out', 'battle', 'time', 'rid', 'purpose', 'life', 'all', 'was', 'world', 'most', 'what', 'meaning', 'the', 'of']

THE TOP 15 WORDS FOR TOPIC #1
['work', 'know', 'weight', 'stop', 'an', 'find', 'from', 'start', 'think', 'with', 'become', 'people', 'get', 'how', 'do']

THE TOP 15 WORDS FOR TOPIC #2
['they', 'facts', 'people', 'most', 'movies', 'books', 'things', 'about', 'that', 'ways', 'good', 'examples', 'some', 'what', 'are']

THE TOP 15 WORDS FOR TOPIC #3
['did', 've', 'about', 'love', 'someone', 'know', 'thing', 'that', 'when', 'think', 'would', 'ever', 'if', 'have', 'you']

THE TOP 15 WORDS FOR TOPIC #4
['have', 'need', 'from', 'time', 'take', 'get', 'ways', 'want', 'possible', 'be', 'like', 'learn', 'way', 'it', 'to']

THE TOP 15 WORDS FOR TOPIC #5
['2016', 'movie', 'books', 'laptop', 'language', 'programming', 'movies', 'ever', 'learn', 'book', 'under', 'way', 'which', 'the', 'best']

THE TOP 15 WORDS FOR TOPIC #6
['that', 'than', 'hate'

The output of the above cell if not all is shown should be:

THE TOP 15 WORDS FOR TOPIC #0
['effects', 'out', 'battle', 'time', 'rid', 'purpose', 'life', 'all', 'was', 'world', 'most', 'what', 'meaning', 'the', 'of']

THE TOP 15 WORDS FOR TOPIC #1
['work', 'know', 'weight', 'stop', 'an', 'find', 'from', 'start', 'think', 'with', 'become', 'people', 'get', 'how', 'do']

THE TOP 15 WORDS FOR TOPIC #2
['they', 'facts', 'people', 'most', 'movies', 'books', 'things', 'about', 'that', 'ways', 'good', 'examples', 'some', 'what', 'are']

THE TOP 15 WORDS FOR TOPIC #3
['did', 've', 'about', 'love', 'someone', 'know', 'thing', 'that', 'when', 'think', 'would', 'ever', 'if', 'have', 'you']

THE TOP 15 WORDS FOR TOPIC #4
['have', 'need', 'from', 'time', 'take', 'get', 'ways', 'want', 'possible', 'be', 'like', 'learn', 'way', 'it', 'to']

THE TOP 15 WORDS FOR TOPIC #5
['2016', 'movie', 'books', 'laptop', 'language', 'programming', 'movies', 'ever', 'learn', 'book', 'under', 'way', 'which', 'the', 'best']

THE TOP 15 WORDS FOR TOPIC #6
['that', 'than', 'hate', 'is', 'have', 'many', 'don', 'and', 'did', 'do', 'we', 'not', 'so', 'people', 'why']

THE TOP 15 WORDS FOR TOPIC #7
['lose', 'with', 'weight', 'become', 'an', 'from', 'be', 'learn', 'one', 'find', 'we', 'where', 'get', 'how', 'can']

THE TOP 15 WORDS FOR TOPIC #8
['meaning', 'most', 'the', 'better', 'com', 'way', 'an', 'like', 'that', 'thing', 'or', 'there', 'it', 'what', 'is']

THE TOP 15 WORDS FOR TOPIC #9
['any', 'places', 'live', 'many', 'most', 'which', 'job', 'life', 'where', 'engineering', 'world', 'there', 'the', 'india', 'in']

THE TOP 15 WORDS FOR TOPIC #10
['science', 'western', 'pakistan', 'relationship', 'similarities', 'chinese', 'an', 'compare', 'war', 'differences', 'what', 'the', 'difference', 'between', 'and']

THE TOP 15 WORDS FOR TOPIC #11
['sex', 'take', 'one', 'when', 'long', 'much', 'what', 'have', 'how', 'feel', 'work', 'like', 'mean', 'it', 'does']

THE TOP 15 WORDS FOR TOPIC #12
['learning', 'gate', 'books', 'book', 'preparation', 'new', 'engineering', 'free', 'exam', 'an', 'year', '2017', 'good', 'prepare', 'for']

THE TOP 15 WORDS FOR TOPIC #13
['add', 'delete', 'many', 'instagram', 'people', 'there', 'asked', 'google', 'answer', 'answers', 'ask', 'question', 'questions', 'quora', 'on']

THE TOP 15 WORDS FOR TOPIC #14
['am', 'girlfriend', 'speaking', 'phone', 'writing', 'gmail', 'increase', 'if', 'password', 'me', 'account', 'skills', 'english', 'improve', 'my']

THE TOP 15 WORDS FOR TOPIC #15
['black', 'easiest', 'through', 'home', 'easy', 'much', 'youtube', 'how', 'ways', 'way', 'from', 'earn', 'online', 'make', 'money']

THE TOP 15 WORDS FOR TOPIC #16
['government', 'currency', 'economy', 'india', 'ban', 'indian', 'banning', 'black', 'rupee', 'will', 'rs', 'and', '1000', 'notes', '500']

THE TOP 15 WORDS FOR TOPIC #17
['resolutions', 'most', 'movie', 'moment', 'resolution', 'favourite', 'new', '2017', 'review', 'year', 'was', 'what', 'favorite', 'life', 'your']

THE TOP 15 WORDS FOR TOPIC #18
['us', 'happen', 'election', 'hillary', 'or', 'president', 'clinton', 'win', 'if', 'would', 'donald', 'will', 'who', 'be', 'trump']

THE TOP 15 WORDS FOR TOPIC #19
['be', 'start', 'one', 'their', 'what', 'employees', 'going', 'into', 'new', 'things', 'day', 'at', 'first', 'know', 'should']



# Begin Practice

In [5]:
import spacy
nlp = spacy.load('en_core_web_lg')
assert(nlp)

# This vector is numerically closer to cat than to dandelion
lionVector = nlp(u'lion').vector

# In spacy these vectors are stored as 300 item arrays
assert(len(lionVector) == 300)


In [6]:
# Doc and span objects themselves have vectors derived from the averages of individual token vectors
# This makes it possible to compare entire documents
doc = nlp(u'The quick brown fox jumped over the lazy dog.')

assert(len(doc.vector) == 300)

In [7]:
# Create a three-token doc object
tokens = nlp(u'lion cat pet')

# Iterate through token combinations
for t1 in tokens:
    for t2 in tokens:
        # Built-in similarity method is great for token comparison
        print(t1.text, t2.text, t1.similarity(t2))

# Below we see that cat is more of a pet than it is a lion

lion lion 1.0
lion cat 0.3854507803916931
lion pet 0.20031584799289703
cat lion 0.3854507803916931
cat cat 1.0
cat pet 0.732966423034668
pet lion 0.20031584799289703
pet cat 0.732966423034668
pet pet 1.0


In [12]:
# tokens = nlp(u'auditor engineer superstar doctor student celebrity actor')

# for t1 in tokens:
#     for t2 in tokens:
#         if t1 == t2: continue
#         print(t1.text, t2.text, t1.similarity(t2))
#     print()

In [14]:
from scipy import spatial

cosine_similarity = lambda x, y: 1- spatial.distance.cosine(x,y)

king = nlp.vocab['king'].vector
man = nlp.vocab['man'].vector
woman = nlp.vocab['woman'].vector

# Now to find the closest vector in the vocabulary to the result of "man" - "woman" + "queen"
new_vector = king - man + woman

computed_similarities = []

for word in nlp.vocab:
    # Ignore words without vectors and mixed-case words
    if not(word.has_vector) or not(word.is_lower) or not(word.is_alpha): continue
    # Get the similarity and add it to the list
    similarity = cosine_similarity(new_vector, word.vector)
    computed_similarities.append((word, similarity))

computed_similarities = sorted(computed_similarities, key=lambda item: -item[1])

for i in computed_similarities[:10]:
    print(i[0].text)


king
the
and
that
where
she
they
woman
there
should


In [15]:
import pandas as pd
npr = pd.read_csv('npr.csv')
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = cv.fit_transform(npr['Article'])
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.decomposition import LatentDirichletAllocation

LDA = LatentDirichletAllocation(n_components=7, random_state=42)
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [19]:
assert(len(LDA.components_) == 7)

LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [20]:
len(LDA.components_[0])

54777

In [39]:
from numpy import single


single_topic = LDA.components_[0]

# Returns the indices that would sort this array
print(single_topic.argsort())
argumentIndices = single_topic.argsort()

# Word that represents this topic the least
print(single_topic[argumentIndices[0]])

# Word that represents this topic the most
print(single_topic[argumentIndices[-1]])

indexList = []
print("Top 10 most representative words for this topic: ")
for i in single_topic.argsort()[-10:]:
    indexList.append(i)
    print(i)

print("\nNow in string flavor: ")
for index in indexList:
    print(cv.get_feature_names_out()[index])

leastFavorite = [i for i in single_topic.argsort()[:10]]
print("\n Least favorite: ")
for idx in leastFavorite:
    print(cv.get_feature_names_out()[idx])

[ 2475 18302 35285 ... 22673 42561 42993]
0.1428571430851871
6247.245510521083
Top 10 most representative words for this topic: 
33390
36310
21228
10425
31464
8149
36283
22673
42561
42993

Now in string flavor: 
new
percent
government
company
million
care
people
health
said
says

 Least favorite: 
alliterative
fcbd
overstreet
skippable
isayama
cbldf
mechanika
funnies
jughead
freecomicbookday
